name: sberry
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - samtools==1.10
  - biopython==1.78
  - longshot==0.4.1
  - minimap2==2.17
  - mummer4==4.0.0beta2
  - networkx==2.5
  - numpy==1.19.1
  - pygraphviz==1.3
  - pysam==0.16.0.1
  - python==3.7.9
  - pyvcf==0.6.8
  - vcflib==1.0.1
  - wtdbg==2.5
